from delivery_strategies.abstract_delivery_strategy import AbsDeliveryStrategy
from delivery_strategies.fedex import FedExDelivery
from delivery_strategies.opay import OpayDelivery
from delivery_strategies.postal import PostalDelivery
